# Generated by Django 4.1.7 on 2023-12-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='nik',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nikibu',
            field=models.BigIntegerField(),
        ),
    ]
